version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-checkout
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5673:5672'
      - '15673:15672'
    env_file:
      - ./rabbitmq.env
